version: '3.8'

services:
  node_backend:
    container_name: express
    image: express:0.0.4
    build:
      context: .
    ports:
      - "8001:8000"
    environment:
      DB_HOST: node_db
      DB_PASSWORD: 123
      restart: always
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: postgres
    ports:
      - "5444:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: express
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always


  node_pgadmin:
    container_name: node_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5051:80"


networks:
  new:
    driver: bridge

volumes:
  nps_data: { }
